name: exact_cover_dlx
description: Generic exact cover solver based on Dancing Links (DLX).
version: 0.1.0
homepage: https://github.com/PeterOmbodi/caesar-s_calendar
repository: https://github.com/PeterOmbodi/caesar-s_calendar
issue_tracker: https://github.com/PeterOmbodi/caesar-s_calendar/issues
topics:
  - exact-cover
  - dlx
  - dancing-links
  - sudoku
  - algorithms

environment:
  sdk: '>=3.10.0 <4.0.0'

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
