// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1SLvdHQ4E1cCjW1vq5gmh3Zror8Oa1pk',
    appId: '1:991187302399:web:268b9df8f5376f1ff7d9ca',
    messagingSenderId: '991187302399',
    projectId: 'caesar-puzzle-673a2',
    authDomain: 'caesar-puzzle-673a2.firebaseapp.com',
    storageBucket: 'caesar-puzzle-673a2.firebasestorage.app',
    measurementId: 'G-SFSLY07FNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbafpxAg0lYmPNkHGPaQL2VwGKPER-JCU',
    appId: '1:991187302399:android:e4bff8f133fd0e07f7d9ca',
    messagingSenderId: '991187302399',
    projectId: 'caesar-puzzle-673a2',
    storageBucket: 'caesar-puzzle-673a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa9y9Cp5Ud_qgy7OUh1HrAAIP4Ec3u1ng',
    appId: '1:991187302399:ios:49442449fc98abb6f7d9ca',
    messagingSenderId: '991187302399',
    projectId: 'caesar-puzzle-673a2',
    storageBucket: 'caesar-puzzle-673a2.firebasestorage.app',
    iosBundleId: 'com.peter.ombodi.caesarcalendar.caesarPuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa9y9Cp5Ud_qgy7OUh1HrAAIP4Ec3u1ng',
    appId: '1:991187302399:ios:49442449fc98abb6f7d9ca',
    messagingSenderId: '991187302399',
    projectId: 'caesar-puzzle-673a2',
    storageBucket: 'caesar-puzzle-673a2.firebasestorage.app',
    iosBundleId: 'com.peter.ombodi.caesarcalendar.caesarPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1SLvdHQ4E1cCjW1vq5gmh3Zror8Oa1pk',
    appId: '1:991187302399:web:ac654413fe02a0dff7d9ca',
    messagingSenderId: '991187302399',
    projectId: 'caesar-puzzle-673a2',
    authDomain: 'caesar-puzzle-673a2.firebaseapp.com',
    storageBucket: 'caesar-puzzle-673a2.firebasestorage.app',
    measurementId: 'G-NNK01W1Z7N',
  );
}
