name: Deploy Flutter Web to GH Pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart run build_runner build -d
      - run: dart run intl_utils:generate
      - run: flutter build web --release --base-href /caesar-s_calendar/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
